apiVersion: v1
kind: Pod
metadata:
  name: helloworld-api
  labels:
    app: helloworld-api
spec:
  containers:
    - name: helloworldapi
      image: helloworldapi:latest
      imagePullPolicy: Never
      ports:
      - containerPort: 8080
