apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
spec:
  selector:
    app: helloworld-api
  type: NodePort
  ports:
    - name: http
      nodePort: 30950
      targetPort: 8080
      port: 8080